version = 0.1

[default.global.parameters]
stack_name = "aws-resume-matcher"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
s3_prefix = "aws-resume-matcher"
parameter_overrides = "ResumeBucket=\"CHANGE_ME_BUCKET\" ResumeKey=\"resume.txt\" ApiPath=\"/match\""
